# Generated by Django 5.1.2 on 2024-10-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
